### ISSUE TITLE
There are two copies of "48.rom" and three copies of "manic.sna" in the repo

### ISSUE THREAD

**Issue by hippietrail** [shaymanjohn/speccyMac#19]
speccyMac/48.rom
speccyMac/speccyMac/Games/manic.sna
speccyMac/speccyMac/48.rom
speccyMac/speccyMac/manic.sna
speccyMac/manic.sna

I'm assuming the copy of the rom in the root directory is the surplus one?

**Comment by shaymanjohn** [comment]
Sounds like an error, feel free to raise a PR and remove them 👍
