### ISSUE TITLE
After one game snapshot fails with an unemulated instruction, subsequent snapshots will not run

### ISSUE THREAD

**Issue by hippietrail** [shaymanjohn/speccyMac#22]
For instance my .z80 of Chase HQ stops with:

Unemulated Instruction:

RRC (HL)
Instruction number: E
Section: z80+cb

<img width="275" alt="Screen Shot 2022-08-23 at 1 45 38 pm" src="https://user-images.githubusercontent.com/533619/186079850-ff35271c-a69d-4972-a8f6-17d90b65079a.png">

After clicking on `OK` choosing any other snapshot from the `Load` button causes the snapshot to load but not to run.

**Comment by shaymanjohn** [comment]
On reporting an unemulated instruction, running is set to false.
Probably just needs setting to true on next load of an image.

**Comment by shaymanjohn** [comment]
PR raised https://github.com/shaymanjohn/speccyMac/pull/23
