### ISSUE TITLE
No graphics other than border colour which fills the whole window

### ISSUE THREAD

**Issue by hippietrail** [shaymanjohn/speccyMac#9]
Running the released version on an M1 MacBook Air / Monterey

I see a window with the "Load game" button in the top right corner. The window is a grey colour like the Speccy's "white".

On loading any game I see no graphics but can hear all of the ones that start playing a tune or emitting sound effects. Games which set the border colour change the whole window to that colour. Manic Miner changes the window colour as the music plays, but nothing else is visible.

**Comment by shaymanjohn** [comment]
Hi @hippietrail - thanks for posting!

Which branch are you running? On my M1 Mac running Monterey, version 12.5 (21G72), and running the `dev` branch, I get this when running:
<img width="832" alt="Screenshot 2022-08-04 at 11 15 49" src="https://user-images.githubusercontent.com/622889/182823485-96a1371a-53a3-42b2-abcb-8801bc79880b.png">

I'm running on Xcode 13.4.1 (13F100)

Sounds like the emulatorScreen object in the Main storyboard isn't working correctly. Is your Main.storyboard file showing any source control changes? If so, discard any changes and retry...

Other than that I'm puzzled...

**Comment by hippietrail** [comment]
I didn't try building from source. I've got so many windows and tabs open that I doubt XCode would open.

About says "Version 0.5 (20170902)". I can only see one release of the app as opposed to the source. Is there a way to get the current version as a built app? Or is there debug info to see in the Console?

(I was actually looking for a Mac project with with bitmap graphics and no SDL2 to learn from the source how to do old school graphics.)

**Comment by shaymanjohn** [comment]
Ah ok, that makes more sense.
I've added an M1 / Monterey release here: https://github.com/shaymanjohn/speccyMac/releases/tag/v0.8
Fingers crossed.

**Comment by hippietrail** [comment]
Thanks!

The new version resets like a Speccy and shows the copyright. But now when I choose any game nothing happens. Nothing happens when I click the mode button either. The about box tells me version is now: Version 0.8 (20190929)

**Comment by shaymanjohn** [comment]
Ah ok, looks like a problem with release archive. 
Can you try this one when you get some time, it's built for M1:
https://github.com/shaymanjohn/speccyMac/releases/tag/v0.8

**Comment by hippietrail** [comment]
Version 0.8 (20190929) is the same but now it seems to work great.

The mode button doesn't seem to change anything. And sometimes there are many thin horizontal lines in the border/background when it's changing colour. Are those expected?

**Comment by shaymanjohn** [comment]
Yeh, the mode button is very subtle so that's ok.
The many thin horizontal lines is a bug caused by me failure to get the border working correctly - I recently moved from only having one border colour, to the border being composed of many lines (this was to be able to emulate games that actually split the border colour deliberately, etc) - but there's a problem with my code somewhere...

**Comment by hippietrail** [comment]
Thanks then it seems the problem is solved. I may add some more issues now that it's working and will play with the source later.
